# This Kubernetes Secret contains sensitive environment variables for the myapps application.
# The `myapps-env` Secret includes:
# - `SECRET_KEY`: The secret key used for application security
# - `QUESTION_URL`: The URL for the API that provides questions
# - `DATABASE_URL`: The connection string for the application's database
# - `email_key`: The API key for the email service
# - `email_`: The email address used for the application

# This Kubernetes Secret contains sensitive credentials for the Postgres database used by the application.
# The `postgres-secret` Secret includes:
# - `POSTGRES_DB`: The name of the database
# - `POSTGRES_USER`: The username for the database
# - `POSTGRES_PASSWORD`: The password for the database user

apiVersion: v1
kind: Secret
metadata:
  name: myapps-env
type: Opaque
data:
  # Base64-encoded values of the environment variables
  SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  QUESTION_URL: aHR0cHM6Ly9leGFtcGxlLmNvbS9hcGkvcXVlc3Rpb25z
  DATABASE_URL: c3FsaXRlOi8vL3BhdGgvdG8vZGF0YWJhc2UuZGI=
  email_key: eW91cl9lbWFpbF9hcHBfa2V5
  email_: eW91cl9lbWFpbEBleGFtcGxlLmNvbQ==


---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: YXBwZGF0YWJhc2U=
  POSTGRES_USER: YXBwdXNlcg==
  POSTGRES_PASSWORD: NUZWbiNWcSFkTHokOVA2MygwUjE=

